title: "Morg's Demo Site"
author:
  name: Morgan Smith
  email: smithmor@grinnell.edu
description: >
  Waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { icon: "github", title: "Minima Theme repository at GitHub", url: "https://github.com/jekyll/minima" }
    - { icon: "x-twitter", title: "Jekyll profile at X (formerly Twitter)", url: "https://x.com/jekyllrb" }
  show_excerpts: true
  skin: solarized # Options: auto, classic, dark, solarized, solarized-light, solarized-dark

# Build settings
baseurl: /mincomp-demo
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]
